"""empty message

Revision ID: 2f4cf169d287
Revises: 
Create Date: 2025-01-24 21:26:21.722428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2f4cf169d287'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_foreign_currency_accounts_account_no', table_name='foreign_currency_accounts')
    op.drop_index('ix_foreign_currency_accounts_id', table_name='foreign_currency_accounts')
    op.drop_table('foreign_currency_accounts')
    op.drop_index('id_no', table_name='signatories')
    op.drop_index('ix_signatories_id', table_name='signatories')
    op.drop_index('name', table_name='signatories')
    op.drop_table('signatories')
    op.drop_index('ix_personal_documents_id', table_name='personal_documents')
    op.drop_table('personal_documents')
    op.drop_index('ix_personal_loans_id', table_name='personal_loans')
    op.drop_table('personal_loans')
    op.drop_index('ix_business_loans_id', table_name='business_loans')
    op.drop_table('business_loans')
    op.drop_index('ix_client_help_id', table_name='client_help')
    op.drop_index('ix_client_help_owner_customer_no', table_name='client_help')
    op.drop_table('client_help')
    op.drop_index('ix_corporate_accounts_account_no', table_name='corporate_accounts')
    op.drop_index('ix_corporate_accounts_id', table_name='corporate_accounts')
    op.drop_table('corporate_accounts')
    op.drop_index('ix_personal_accounts_account_no', table_name='personal_accounts')
    op.drop_index('ix_personal_accounts_id', table_name='personal_accounts')
    op.drop_table('personal_accounts')
    op.drop_index('ix_prepaid_cards_id', table_name='prepaid_cards')
    op.drop_table('prepaid_cards')
    op.drop_table('customer_rm_association')
    op.drop_index('ix_mortgages_id', table_name='mortgages')
    op.drop_table('mortgages')
    op.drop_index('ix_wallet_topups_account', table_name='wallet_topups')
    op.drop_index('ix_wallet_topups_id', table_name='wallet_topups')
    op.drop_index('ref_no', table_name='wallet_topups')
    op.drop_table('wallet_topups')
    op.drop_index('ix_debit_cards_id', table_name='debit_cards')
    op.drop_table('debit_cards')
    op.drop_index('email', table_name='customers')
    op.drop_index('ix_customers_customer_no', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_credit_cards_id', table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index('ix_term_deposits_id', table_name='term_deposits')
    op.drop_table('term_deposits')
    op.drop_index('ix_client_reports_id', table_name='client_reports')
    op.drop_index('ix_client_reports_owner_customer_no', table_name='client_reports')
    op.drop_table('client_reports')
    op.drop_index('ix_buy_goods_and_services_account', table_name='buy_goods_and_services')
    op.drop_index('ix_buy_goods_and_services_id', table_name='buy_goods_and_services')
    op.drop_index('ref_no', table_name='buy_goods_and_services')
    op.drop_table('buy_goods_and_services')
    op.drop_index('ix_transfer_account', table_name='transfer')
    op.drop_index('ix_transfer_id', table_name='transfer')
    op.drop_index('ref_no', table_name='transfer')
    op.drop_table('transfer')
    op.drop_index('ix_mortgage_documents_id', table_name='mortgage_documents')
    op.drop_table('mortgage_documents')
    op.drop_index('ix_bill_payments_account', table_name='bill_payments')
    op.drop_index('ix_bill_payments_id', table_name='bill_payments')
    op.drop_index('ref_no', table_name='bill_payments')
    op.drop_table('bill_payments')
    op.drop_index('email', table_name='relationship_managers')
    op.drop_index('ix_relationship_managers_employee_id', table_name='relationship_managers')
    op.drop_index('ix_relationship_managers_id', table_name='relationship_managers')
    op.drop_table('relationship_managers')
    op.drop_index('ix_loan_documents_id', table_name='loan_documents')
    op.drop_table('loan_documents')
    op.drop_index('ix_fca_documents_id', table_name='fca_documents')
    op.drop_table('fca_documents')
    op.drop_index('ix_corporate_documents_id', table_name='corporate_documents')
    op.drop_table('corporate_documents')
    op.drop_index('ix_airtime_account', table_name='airtime')
    op.drop_index('ix_airtime_id', table_name='airtime')
    op.drop_index('ref_no', table_name='airtime')
    op.drop_table('airtime')
    op.drop_index('file_name', table_name='signatures')
    op.drop_index('ix_signatures_id', table_name='signatures')
    op.drop_table('signatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signatures',
    sa.Column('file_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('signatory_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('signatory_id', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['signatory_id'], ['signatories.id_no'], name='signatures_ibfk_2'),
    sa.ForeignKeyConstraint(['signatory_name'], ['signatories.name'], name='signatures_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_signatures_id', 'signatures', ['id'], unique=True)
    op.create_index('file_name', 'signatures', ['file_name'], unique=True)
    op.create_table('airtime',
    sa.Column('transaction_type', mysql.VARCHAR(length=23), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ref_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beneficiary', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='airtime_ibfk_1'),
    sa.PrimaryKeyConstraint('ref_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ref_no', 'airtime', ['ref_no'], unique=True)
    op.create_index('ix_airtime_id', 'airtime', ['id'], unique=True)
    op.create_index('ix_airtime_account', 'airtime', ['account'], unique=False)
    op.create_table('corporate_documents',
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['corporate_accounts.account_no'], name='corporate_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_corporate_documents_id', 'corporate_documents', ['id'], unique=True)
    op.create_table('fca_documents',
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['foreign_currency_accounts.account_no'], name='fca_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fca_documents_id', 'fca_documents', ['id'], unique=True)
    op.create_table('loan_documents',
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['business_loans.account_no'], name='loan_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_loan_documents_id', 'loan_documents', ['id'], unique=True)
    op.create_table('relationship_managers',
    sa.Column('department', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_relationship_managers_id', 'relationship_managers', ['id'], unique=True)
    op.create_index('ix_relationship_managers_employee_id', 'relationship_managers', ['employee_id'], unique=True)
    op.create_index('email', 'relationship_managers', ['email'], unique=True)
    op.create_table('bill_payments',
    sa.Column('account_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ref_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beneficiary', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='bill_payments_ibfk_1'),
    sa.PrimaryKeyConstraint('ref_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ref_no', 'bill_payments', ['ref_no'], unique=True)
    op.create_index('ix_bill_payments_id', 'bill_payments', ['id'], unique=True)
    op.create_index('ix_bill_payments_account', 'bill_payments', ['account'], unique=False)
    op.create_table('mortgage_documents',
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['mortgages.account_no'], name='mortgage_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mortgage_documents_id', 'mortgage_documents', ['id'], unique=True)
    op.create_table('transfer',
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ref_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beneficiary', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='transfer_ibfk_1'),
    sa.PrimaryKeyConstraint('ref_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ref_no', 'transfer', ['ref_no'], unique=True)
    op.create_index('ix_transfer_id', 'transfer', ['id'], unique=True)
    op.create_index('ix_transfer_account', 'transfer', ['account'], unique=False)
    op.create_table('buy_goods_and_services',
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=23), nullable=False),
    sa.Column('ref_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beneficiary', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='buy_goods_and_services_ibfk_1'),
    sa.PrimaryKeyConstraint('ref_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ref_no', 'buy_goods_and_services', ['ref_no'], unique=True)
    op.create_index('ix_buy_goods_and_services_id', 'buy_goods_and_services', ['id'], unique=True)
    op.create_index('ix_buy_goods_and_services_account', 'buy_goods_and_services', ['account'], unique=False)
    op.create_table('client_reports',
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('status_resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='client_reports_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_client_reports_owner_customer_no', 'client_reports', ['owner_customer_no'], unique=False)
    op.create_index('ix_client_reports_id', 'client_reports', ['id'], unique=True)
    op.create_table('term_deposits',
    sa.Column('account_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('maturity_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maturity_date', mysql.DATETIME(), nullable=False),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('interest', mysql.FLOAT(), nullable=False),
    sa.Column('accumulated_value', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='term_deposits_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_term_deposits_id', 'term_deposits', ['id'], unique=True)
    op.create_table('credit_cards',
    sa.Column('card_type', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('annual_income', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employment_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limit', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('card_classification', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('date_issued', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('delivery_option', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('loyalty_point', mysql.FLOAT(), nullable=False),
    sa.Column('card_no', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='credit_cards_ibfk_1'),
    sa.PrimaryKeyConstraint('card_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_credit_cards_id', 'credit_cards', ['id'], unique=True)
    op.create_table('customers',
    sa.Column('pin', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('customer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credit_score', mysql.FLOAT(), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_customers_id', 'customers', ['id'], unique=True)
    op.create_index('ix_customers_customer_no', 'customers', ['customer_no'], unique=True)
    op.create_index('email', 'customers', ['email'], unique=True)
    op.create_table('debit_cards',
    sa.Column('card_no', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('card_type', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('account_attached_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_classification', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('date_issued', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('delivery_option', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('loyalty_point', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_attached_no'], ['personal_accounts.account_no'], name='debit_cards_ibfk_1'),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='debit_cards_ibfk_2'),
    sa.PrimaryKeyConstraint('card_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_debit_cards_id', 'debit_cards', ['id'], unique=True)
    op.create_table('wallet_topups',
    sa.Column('transaction_type', mysql.VARCHAR(length=23), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_provider', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ref_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('beneficiary', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='wallet_topups_ibfk_1'),
    sa.PrimaryKeyConstraint('ref_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ref_no', 'wallet_topups', ['ref_no'], unique=True)
    op.create_index('ix_wallet_topups_id', 'wallet_topups', ['id'], unique=True)
    op.create_index('ix_wallet_topups_account', 'wallet_topups', ['account'], unique=False)
    op.create_table('mortgages',
    sa.Column('employment_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('annual_income', mysql.FLOAT(), nullable=False),
    sa.Column('payback_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('property_address', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('property_value', mysql.FLOAT(), nullable=False),
    sa.Column('down_payment', mysql.FLOAT(), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('property_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_status', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('maturity_date', mysql.DATETIME(), nullable=False),
    sa.Column('compounding_frequency', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('last_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('next_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('outstanding_amount', mysql.FLOAT(), nullable=False),
    sa.Column('purpose', mysql.TEXT(), nullable=False),
    sa.Column('accrued_interest', mysql.FLOAT(), nullable=False),
    sa.Column('principal_paid', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='mortgages_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mortgages_id', 'mortgages', ['id'], unique=True)
    op.create_table('customer_rm_association',
    sa.Column('customer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationship_manager_id', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_no'], ['customers.customer_no'], name='customer_rm_association_ibfk_1'),
    sa.ForeignKeyConstraint(['relationship_manager_id'], ['relationship_managers.employee_id'], name='customer_rm_association_ibfk_2'),
    sa.PrimaryKeyConstraint('customer_no', 'relationship_manager_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prepaid_cards',
    sa.Column('card_type', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intended_usage', mysql.TEXT(), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('date_issued', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('delivery_option', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('loyalty_point', mysql.FLOAT(), nullable=False),
    sa.Column('card_no', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='prepaid_cards_ibfk_1'),
    sa.PrimaryKeyConstraint('card_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_prepaid_cards_id', 'prepaid_cards', ['id'], unique=True)
    op.create_table('personal_accounts',
    sa.Column('nssf_no', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('nok_relationship', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('next_of_kin', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('next_of_kin_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('overdraft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('employment_status', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_no', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('kra_pin', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_balance', mysql.FLOAT(), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_status', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('annual_income', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_of_funds', mysql.TEXT(), nullable=False),
    sa.Column('intended_usage', mysql.TEXT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='personal_accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_personal_accounts_id', 'personal_accounts', ['id'], unique=True)
    op.create_index('ix_personal_accounts_account_no', 'personal_accounts', ['account_no'], unique=True)
    op.create_table('corporate_accounts',
    sa.Column('overdraft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('debit_card_no', mysql.VARCHAR(length=17), nullable=True),
    sa.Column('account_no', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_no', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('kra_pin', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_balance', mysql.FLOAT(), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_status', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('annual_income', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_of_funds', mysql.TEXT(), nullable=False),
    sa.Column('intended_usage', mysql.TEXT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['debit_card_no'], ['debit_cards.card_no'], name='corporate_accounts_ibfk_1'),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='corporate_accounts_ibfk_2'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_corporate_accounts_id', 'corporate_accounts', ['id'], unique=True)
    op.create_index('ix_corporate_accounts_account_no', 'corporate_accounts', ['account_no'], unique=True)
    op.create_table('client_help',
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('status_resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='client_help_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_client_help_owner_customer_no', 'client_help', ['owner_customer_no'], unique=False)
    op.create_index('ix_client_help_id', 'client_help', ['id'], unique=True)
    op.create_table('business_loans',
    sa.Column('id_no', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('pmargin', mysql.FLOAT(), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('disposable_amount', mysql.FLOAT(), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payback_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_status', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('maturity_date', mysql.DATETIME(), nullable=False),
    sa.Column('compounding_frequency', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('last_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('next_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('outstanding_amount', mysql.FLOAT(), nullable=False),
    sa.Column('purpose', mysql.TEXT(), nullable=False),
    sa.Column('accrued_interest', mysql.FLOAT(), nullable=False),
    sa.Column('principal_paid', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='business_loans_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_business_loans_id', 'business_loans', ['id'], unique=True)
    op.create_table('personal_loans',
    sa.Column('employment_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('disposable_amount', mysql.FLOAT(), nullable=False),
    sa.Column('monthly_income', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payback_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_status', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('maturity_date', mysql.DATETIME(), nullable=False),
    sa.Column('compounding_frequency', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('last_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('next_calculation_date', mysql.DATETIME(), nullable=False),
    sa.Column('outstanding_amount', mysql.FLOAT(), nullable=False),
    sa.Column('purpose', mysql.TEXT(), nullable=False),
    sa.Column('accrued_interest', mysql.FLOAT(), nullable=False),
    sa.Column('principal_paid', mysql.FLOAT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='personal_loans_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_personal_loans_id', 'personal_loans', ['id'], unique=True)
    op.create_table('personal_documents',
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('doc_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['personal_accounts.account_no'], name='personal_documents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_personal_documents_id', 'personal_documents', ['id'], unique=True)
    op.create_table('signatories',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_no', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['corporate_accounts.account_no'], name='signatories_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'signatories', ['name'], unique=True)
    op.create_index('ix_signatories_id', 'signatories', ['id'], unique=True)
    op.create_index('id_no', 'signatories', ['id_no'], unique=True)
    op.create_table('foreign_currency_accounts',
    sa.Column('next_of_kin', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('next_of_kin_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('nok_relationship', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('equivalent_balance', mysql.FLOAT(), nullable=False),
    sa.Column('account_no', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_no', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('kra_pin', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('account_balance', mysql.FLOAT(), nullable=False),
    sa.Column('owner_customer_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_status', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=False),
    sa.Column('annual_income', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_of_funds', mysql.TEXT(), nullable=False),
    sa.Column('intended_usage', mysql.TEXT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_customer_no'], ['customers.customer_no'], name='foreign_currency_accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('account_no', 'id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_foreign_currency_accounts_id', 'foreign_currency_accounts', ['id'], unique=True)
    op.create_index('ix_foreign_currency_accounts_account_no', 'foreign_currency_accounts', ['account_no'], unique=True)
    # ### end Alembic commands ###
